import type { ProjectFrontmatter } from "@/types/project";

export const placeholderProjects: ProjectFrontmatter[] = [
  {
    title: "Simpler workflows for rotational graziers",
    label: "Atlas Carbon | Simpler workflows for rotational graziers",
    slug: "atlas-carbon",
    client: "Atlas Carbon",
    role: "Lead Product Designer",
    year: 2025,
    summary:
      "Translated messy real-world grazing behaviour into a functional system model that became the MVP backbone.",
    cover: "/images/figma/Work/Atlas.png",
    thumbnail: "/images/figma/Work/Atlas.png",
    accent: "neon",
    palette: "teal",
    coverTone: "light",
    tags: ["AgTech", "0 to 1", "iOS App", "Web App", "Design System"],
    status: "published",
    order: 1,
  },
  {
    title: "Design systems and multi-brand website redesign",
    label: "IAG | Design systems and multi-brand website redesign",
    slug: "iag-design-system",
    client: "IAG",
    role: "Lead UX/UI Designer / Design Systems SME",
    year: 2024,
    summary:
      "Built a comprehensive design system from scratch, standardising processes and delivering 50%+ design efficiency gains across brands.",
    cover: "/images/figma/Work/IAG.png",
    thumbnail: "/images/figma/Work/IAG.png",
    accent: "magenta",
    palette: "navy",
    coverTone: "light",
    tags: ["Insurance", "Design System", "Website Redesign", "AEM"],
    status: "published",
    order: 2,
  },
  {
    title: "Conversational AI users actually trust",
    label: "AWS | Conversational AI users actually trust",
    slug: "aws-chatbot",
    client: "AWS",
    role: "Design Lead",
    year: 2024,
    summary:
      "Reframed a bloated assistant into a conversational surface people actually trust to complete work.",
    cover: "/images/figma/Work/AWS.png",
    thumbnail: "/images/figma/Work/AWS.png",
    accent: "orange",
    palette: "navy",
    tags: ["Enterprise", "Conversational AI", "Chatbot"],
    status: "published",
    order: 3,
  },
  {
    title: "One calm planning surface for fuel ops",
    label: "bp | One calm planning surface for fuel ops",
    slug: "bp",
    client: "bp",
    role: "Experience Designer",
    year: 2023,
    summary:
      "Unified a fragmented planning ecosystem into a calm, data-confident operational surface for fuel supply planners.",
    cover: "/images/figma/Work/bp.png",
    thumbnail: "/images/figma/Work/bp.png",
    accent: "neon",
    palette: "navy",
    coverTone: "light",
    tags: ["Energy", "ERP Dashboard"],
    status: "published",
    order: 4,
  },
  {
    title: "21.9% conversion lift in joinery ops",
    label: "Carell | 21.9% conversion lift in joinery ops",
    slug: "carell",
    client: "Carell",
    role: "Lead UX/UI Designer",
    year: 2025,
    summary:
      "Turned scattered spreadsheets, phone calls, and paper job sheets into a single, on-site mobile platform for joinery production and installation.",
    cover: "/images/figma/Work/Carell.png",
    thumbnail: "/images/figma/Work/Carell.png",
    accent: "orange",
    palette: "navy",
    tags: ["Construction", "Mobile App"],
    status: "published",
    order: 5,
  },
];
